model:
  hidden_dims : [1536, 768, 192]


data_loader:
  batch_size : 512

training:
  n_epochs : 500
  eval_every_epochs: 50
  save_interm_embeds : False
  lr : !!float 1e-2
  scale : !!float 1
  loss_class : "infonce.InfoNCECauchy"



