model:
  hidden_dims : [1536, 768, 192]

data_loader:
  augmentation: "data_stuff.AbstractAndCropDataset"
  batch_size : 256


training:
  n_epochs : 5
  eval_every_epochs: 5
  save_interm_embeds : True
  lr : 
  - !!float 5e-2 
  - !!float 2e-2 
  - !!float 1e-2 
  - !!float 5e-3
  - !!float 2e-3
  - !!float 1e-3
  - !!float 1e-4
  scale : !!float 1
  loss_class : "infonce.InfoNCECauchy"
 

hyperparameter_sweep:
  - training.lr

