model:
  hidden_dims : [1536, 768, 192]


data_loader:
  batch_size : 512

training:
  n_epochs : 1
  eval_every_epochs: 1
  save_interm_embeds : False 
  lr : 
  - !!float 1e-3
  - !!float 2e-3
  scale:
  - 20
  - 10

hyperparameter_sweep:
- training.lr
- training.scale